version: '2'

services:
  web:
    build: .
    image: auth
    command: 'amber watch'
    working_dir: /app/user
    environment:
      DATABASE_URL: mysql://admin:password@db:3306/auth_development
      SMTP_URL: mail:1025
    ports:
      - '3000:3000'
    depends_on:
      - db
      - mail
    volumes:
      - '.:/app/user'

  migrate:
    build: .
    image: auth
    command: bash -c 'while ! nc -q 1 db 3306 </dev/null; do sleep 1; done && amber migrate up'
    working_dir: /app/user
    environment:
      DATABASE_URL: mysql://admin:password@db:3306/auth_development
    volumes:
      - '.:/app/user'
    depends_on:
      - db

  mail:
    image: drujensen/mailcatcher:latest
    ports:
      - '1025:1025'
      - '1080:1080'

  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: auth_development
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - 'db:/var/lib/mysql'

volumes:
  db:
